version: '3.4'

services:
  usuariosapp.api:
    container_name: usuariosapp_api
    image: ${DOCKER_REGISTRY-}usuariosappapi
    build:
      context: .
      dockerfile: UsuariosApp.API/Dockerfile
    ports:
        - 54321:80
    depends_on:
        - db
        - rabbitmq
  db:
    container_name: usuariosapp_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "@Coti2023"
        ACCEPT_EULA: "Y"
    ports:
        - "1433:1433"
  rabbitmq:
    container_name: usuariosapp_rabbitmq
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    ports:
        - "5672:5672"
        - "15672:15672"
    expose:
        - 5672
        - 15672
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest